#!/bin/bash
#
#include lib
. ~/lib/sh/libshellutils.sh


#######################################
# Echo a message in the specified color
# Arguments:
#   COLOR
#   MESSAGE
# Outputs:
#   Writes to stdout
#######################################
print_color $1 $2
exit 0
